apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: hello-world-scala
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "hello-world-scala:7.0"
  imagePullPolicy: IfNotPresent
  mainClass: HelloWorld
  mainApplicationFile: "local:///app/helloworld.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
    labels:
      version: 3.1.1
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
  sparkConf:
    "spark.master": "http:///127.0.0.1:8080"
    "spark.kubernetes.container.image": "hello-world-scala:7.0"    